// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm7rqvq4GlCm-25GmslYn7MWUhV9Jecko',
    appId: '1:390301417232:web:fcd074ffeff8368d43af95',
    messagingSenderId: '390301417232',
    projectId: 'conta-certa-8948e',
    authDomain: 'conta-certa-8948e.firebaseapp.com',
    storageBucket: 'conta-certa-8948e.appspot.com',
    measurementId: 'G-KDBNC1RCQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUNc2WyXhmdhvLFGSPKww3k6LrbxnaoDk',
    appId: '1:390301417232:android:9fd65edb45b8ccda43af95',
    messagingSenderId: '390301417232',
    projectId: 'conta-certa-8948e',
    storageBucket: 'conta-certa-8948e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy-nO5WCsTeiwOZLvKqPQJnWLNz3F14Bo',
    appId: '1:390301417232:ios:9a2b205b237ffc0d43af95',
    messagingSenderId: '390301417232',
    projectId: 'conta-certa-8948e',
    storageBucket: 'conta-certa-8948e.appspot.com',
    iosBundleId: 'com.example.simpleProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy-nO5WCsTeiwOZLvKqPQJnWLNz3F14Bo',
    appId: '1:390301417232:ios:b35f78ada8f046f243af95',
    messagingSenderId: '390301417232',
    projectId: 'conta-certa-8948e',
    storageBucket: 'conta-certa-8948e.appspot.com',
    iosBundleId: 'com.example.simpleProject.RunnerTests',
  );
}
